alwaysShowEliteMobNameTags: false
superMobStackAmount: 50
preventEliteCreeperDamageToPassiveMobs: true
useTitlesForMissingPermissionMessages: true
hideEnchantmentAttributes: false
preventEliteMobConversionOfNamedMobs: true
enableHighCompatibilityMode: false
