doNaturalEliteMobSpawning: true
doSpawnersSpawnEliteMobs: false
eliteMobsSpawnPercentage: 0.2
levelsBetweenEliteMobTiers: 10
superMobStackRange: 15
naturalEliteMobLevelCap: 1500
eliteCreeperExplosionMultiplier: 1.0
doElitesWearArmor: true
doElitesWearHelmets: true
doNaturalEliteMobVisualEffects: true
doSpawnerEliteMobVisualEffects: false
doPowerBuildupVisualEffects: true
doCustomEliteMobsDeathMessages: true
doDisplayMobHealthOnHit: true
doDisplayMobDamageOnHit: true
doEliteMobHealthDisplayOnly: true
doEliteMobDamageDisplayOnly: true
doIncreaseEliteMobLevelBasedOnSpawnDistance: false
distanceBetweenIncrements: 100.0
levelIncreaseAtIncrements: 1.0
hideEliteMobPowersUntilAggro: true
damageToEliteMobMultiplier: 1.0
damageToPlayerMultiplier: 1.0
showCustomBossLocation: true
bossLocationMessage: '&7[EM] &2[点击追踪!]'
