dropProcedurallyGeneratedItems: true
customEnchantmentChance: 0.1
nameFormats:
- $adjective$noun
- $verb$adjective$noun
- $verb$adjective$itemType
- $noun之$itemType
- $verb-er之$itemType
- $verb-er
- $adjective$verb-er
nouns:
- 破晓黎明
- 晚霞
- 天堂
- 地狱
- 天使
- 大天使
- 小天使
- 六翼天使
- 恶魔
- 凝视
- 朋友
- 蝙蝠
- 混沌
- 混乱
- 鸡
- 牛
- 哞菇
- 猪
- 兔
- 羊
- 墨鱼
- 村民
- 洞穴蜘蛛
- 末影人
- 北极熊
- 蜘蛛
- 僵尸猪人
- 烈焰人
- 苦力怕
- 远古守护者
- 末影螨
- 唤魔者
- 溺尸
- 海豚
- 河豚
- 恶魂
- 守护者
- 尸壳
- 岩浆怪
- 潜影贝
- 蠹虫
- 骷髅
- 史莱姆
- 流髑
- 恼鬼
- 卫道士
- 女巫
- 凋灵骷髅
- 僵尸
- 驴
- 马
- 羊驼
- 骡
- 豹猫
- 狼
- 铁傀儡
- 雪傀儡
- 末影龙
- 凋灵
- 幻术士
- 鹦鹉
- 巨人
- 杀手兔
- 史蒂夫
- 祸根
- 混沌
- 万年
- 龙
- 斯芬克斯
- 牛头人
- 冥王
- 灾厄村民
- 灾厄之兽
- 誓言
- 誓言破坏者
- 被遗弃者
- 背叛者
- 犹大
- 光
- 黑暗
- 遗忘
- 影
- 虚空
- 异种
- 狂热者
- 天顶
- 黄昏
- 暮色
- 怪物
- 精英怪物
- 乌利斯特
- 侏儒
- 精灵
- 奥克
- 哥布林
- 侏儒
- 歌利亚
- 轻雾
- 人类
- 半人
- 半兽人
- 兽人
- 亚人
- 牧师
- 巫妖王
- 克苏鲁
- 魔人
- 枭熊
- 斩首者
- 夺心魔
- 帕拉丁
- 九头蛇
- 克拉肯
- 枭熊
- 鲨蜥兽
- 锈蚀怪
- 山之巨人
- 石巨人
- 冰霜巨人
- 烈焰巨人
- 云之巨人
- 风暴巨人
- 土地神
- 巫妖
- 夺心魔
- 伏地魔
- 心魔
- 土巨怪
- 战士
- 男巫
- 圣骑士
- 牧师
- 护林员
- 弓箭手
- 魔法师
- 魔人
- 狼人
- 吸血鬼
- 半人马座
- 猫科动物
- 半巨人
- 食人魔
- 流氓
- 野蛮人
- 吟游诗人
- 德鲁伊
- 和尚
- 巫师
- 术士
- 恶魔猎手
- 死亡骑士
- 神父
- 萨满
- 战士
- 蛇怪
- 嵌合体
- 小鬼
- 森林女神
- 石像鬼
- 丁尼
- 火巨灵
- 幽灵
- 九头蛇
- 克拉肯
- 拉米亚
- 吐槽
- 美杜莎
- 模仿者
- 木乃伊
- 飞马星座
- 大鹏
- 萨蒂尔
- 泰拉斯奎巨兽
- 憎恶
- 食尸鬼
- 树妖
- 独角兽
- 幽灵
- 侍僧
- 角斗士
- 骑士
- 狮鹫
- 掠夺
- 间谍
- 贵族
- 守卫
- 老兵
- 飞龙
- 深渊
- 地狱
- 元素
- 牛头人
- 熊猫人
- 野人
- 被遗忘者
- 雪人
- 女鬼
- 魔蛛
- 不死亡灵
- 暗黑精灵
- 血之精灵
- 德莱尼
- 狼人
- 战争领主
- 女巫
- 法师
- 圣人
- 小偷
- 刺客
- MagmaGuy
- qsefthuopq
- 圣殿骑士
- 驯兽师
- 狂战士
- 发明家
- 职业摔跤手
- 海盗
- 先锋
- 虚空之刃
- 魔眼
- 农夫
- 步兵
- 剑士
- 四星
- 论外
- 奴隶
- 猎犬
- 女猎手
adjectives:
- 美丽之
- 干净之
- 文雅之
- 幻想之
- 腐朽之
- 迷人之
- 长之
- 出色之
- 平凡之
- 深红之
- 深蓝之
- 橙之
- 黄之
- 绿之
- 蓝之
- 紫之
- 灰之
- 荒野之
- 黑之
- 白之
- 死之
- 奇怪之
- 强大之
- 震耳欲聋之
- 雷电之
- 古代之
- 腐烂之
- 虚无之
- 重之
- 神奇之
- 模糊之
- 愤怒之
- 复仇之
- 野蛮之
- 狂暴之
- 最好之
- 眩晕之
- 暴雪之
- 鲜血之
- 沸腾之
- 无穷之
- 勇敢之
- 易碎之
- 颤栗之
- 笨拙之
- 多云之
- 经典之
- 深渊之
- 普通之
- 精致之
- 破损之
- 破碎之
- 危险之
- 黑暗之
- 精英之
- 奇异之
- 真·
- 假·
- 花之
- 狂怒之
- 跃动之
- 泡沫之
- 愚昧之
- 遗忘之
- 幸运之
- 脆弱之
- 疯狂之
- 自由之
- 巨大之
- 神之
- 开心之
- 天堂制造·
- 地狱之
- 浩大之
- 饥饿之
- 冰之
- 非法之
- 无礼之
- 重要之
- 博学之
- 微小之
- 现代之
- 幼稚之
- 中立之
- 干净之
- 新之
- 量产之
- 和平之
- 完美之
- 粉色之
- 塑料之
- 笨重之
- 珍贵之
- 收费之
- 私人之
- 迅捷之
- 稀有之
- 一般之
- 圆之
- 忠诚之
- 咸之
- 科学之
- 二手之
- 秘制之
- 短之
- 强大之
- 甜蜜之
- 紧绷之
- 可怕之
- 狡猾之
- 真·
- 超级
- 毫无防备之
- 独一无二之
- 未知之
- 崭新之
- 非同寻常之
- 用过之
- 有用之
- 无用之
- 珍贵之
- 暴力之
- 绝妙之
- 直死之
- 无价之
- 错误之
- 神之
- 险恶之
- 切割之
verbs:
- 尖锐的
- 狂乱的
- 杀戮的
- 屠夫的
- 毁灭的
- 谋杀的
- 旅行的
- 天使的
- 公开的
- 蔚蓝的
- 狂战士的
- 炽热的
- 北方的
- 残酷的
- 燃烧的
- 船长的
- 天体的
- 冷静的
- 牧师的
- 冷凝的
- 神圣的
- 残酷的
- 致命的
- 狡猾的
- 神圣的
- 龙的
- 天堂的
- 专家的
- 忠实的
- 孤独的
- 狂热的
- 野生的
- 凶猛的
- 燃烧的
- 绿色的
- 激烈的
- 盖亚的
- 闪烁的
- 发光的
- 虔诚的
- 盗墓者的
- 神圣的
- 寒冷的
- 教皇的
- 神圣的
- 国王的
- 骑士的
- 月球的
- 少女的
- 大规模的
- 机械论者的
- 主义的
- 无情的
- 自然的
- 没有感情的
- 亡灵杀手之
- 有害的
- 圣骑士的
- 致命的
- 铂金的
- 汹涌的
- 神圣的
- 圣洁的
- 野蛮的
- 闪烁的
- 尖叫的
- 蛇的
- 闪烁的
- 令人震惊的
- 精神的
- 有毒的
- 教练的
- 神秘的
- 有毒的
- 资深的
- 恶毒的
- 胜利的
- 旺盛的
- 哀号的
- 战士的
- 怪异的
- 巨龙的
- 服主的
- 残缺的
- 天使的
- 恶魔的
- 朗基努斯的
- 炽热的
- 永恒的
- 不朽的
- 传说中的
- 虚幻的
- 神话的
- 神秘的
- 德鲁伊的
- 隔绝的
- 专家的
- 复仇者的
- 破旧的
- 我的
- 你的
- 冰冷的
- Herobrine的
- qsefthuopq的
- 暗黑破坏神的
- 克苏鲁的
- 死神的
- 非洲的
- 欧洲的
- 世界的
- 王的
- 以撒的
- 三星的
- 假的
- 加了特技的
- 不可名状的
- 开光的
- 忠诚的
- 召唤者的
- 暴怒的
- 疯狂的
- 死灵法师的
- 铁匠的
- 异次元的
- 四次元的
- 牛顿的
- 远古的
- 锋利的
- 程序员的
- 单身狗的
- 感染者的
- 中二的
- 无政府主义者的
- 和平主义者的
- 宙斯的
- 赫尔墨斯的
- ?的
- 死而复生的
- 正版的
- 真·
- 不存在的
- 撒旦的
- 平凡的
verb-ers (noun):
- 世界破坏者
- 世界切割者
- 复仇者
- 灰烬使者
- 听风者
- 亵渎者
- 雷霆之怒
- 切割机
- 伐木者
- 切割者
- 隔离者
- 雕刻者
- 记者
- 作弊者
- 筑梦者
- 逐梦者
- 逐暗者
- 裁决者
- 刺客
- 杀手
- 屠戮者
- 破坏者
- 拥抱者
- 观测者
- 时间领主
- 谋杀者
- 冲击者
- 旅者
- 搬运工
- 瞥视者
- 肇事者
- 钢铁之躯
- 召唤者
- 需求者
- 突袭者
- 前锋
- 伏兵
- 推土机
- 风暴召唤者
- 轰炸机
- 弹幕
- 打击者
- 霸主
- 战士
- 锤兵
- 格斗者
- 湮灭者
- 丽影
- 射手
- 冒险家
- 爆破者
- 终结者
- 破碎者
- 撕裂者
- 狙击手
- 爆破者
- 探索者
- 破碎者
- 分裂者
- 筑城者
- 召唤者
- 呐喊者
- 转换者
- 变形者
- 修改者
- 残影
- 传送者
- 替代者
- 改写者
- 进化者
- 猎人
- 追踪者
- 尾随者
- 潜行者
- 暗影神偷
- 起义者
- 隐藏者
- 埋葬者
- 云巅之主
- 影舞者
- 封印者
- 掩饰者
- 阐释者
- 穿越者
- 滑行者
- 吼叫者
- 斧王
- 撕裂者
- 裁剪者
- 约束者
- 雕刻者
- 黑客
- 穿刺者
- 见证者
- 剃须刀
- 矿工
- 钻孔者
- 挖掘者
- 寄生者
- 流浪者
- 入侵者
- 侵略者
- 跑者
- 欺瞒者
- 毁灭者
- 战士
- 搏斗者
- 决斗者
- 争吵者
- 冲击者
- 进攻者
- 封建主义者
- 揭露者
- 飞跃者
- 漏斗
- 隐者
- 吸血鬼
- 弱者
- 伪造者
- 释放者
- 收集者
- 碎裂者
- 推进者
- 慢跑者
- 速跑者
- 童子军
- 探险家
- 挖掘者
- 震颤者
- 参与者
- 洞穴探险者
- 半赫者
- 破坏者
- 渲染者
- 开膛手
- 食植者
- 推进者
- 垄断者
- 针锋
- 捉捕者
- 约束者
- 契合者
- 狙击手
- 攫取者
- 捕捉者
- 鬼影
- 劫掠者
- 吞噬者
- 爬行者
- 潜行者
validMaterials:
  DIAMOND_HELMET: true
  DIAMOND_CHESTPLATE: true
  DIAMOND_LEGGINGS: true
  DIAMOND_BOOTS: true
  DIAMOND_SWORD: true
  DIAMOND_AXE: true
  DIAMOND_HOE: true
  DIAMOND_PICKAXE: true
  DIAMOND_SHOVEL: true
  IRON_HELMET: true
  IRON_CHESTPLATE: true
  IRON_LEGGINGS: true
  IRON_BOOTS: true
  IRON_SWORD: true
  IRON_AXE: true
  IRON_HOE: true
  IRON_PICKAXE: true
  IRON_SHOVEL: true
  GOLDEN_HELMET: true
  GOLDEN_CHESTPLATE: true
  GOLDEN_LEGGINGS: true
  GOLDEN_BOOTS: true
  GOLDEN_SWORD: true
  GOLDEN_AXE: true
  GOLDEN_HOE: true
  GOLDEN_PICKAXE: true
  GOLDEN_SHOVEL: true
  CHAINMAIL_HELMET: true
  CHAINMAIL_CHESTPLATE: true
  CHAINMAIL_LEGGINGS: true
  CHAINMAIL_BOOTS: true
  LEATHER_HELMET: true
  LEATHER_CHESTPLATE: true
  LEATHER_LEGGINGS: true
  LEATHER_BOOTS: true
  STONE_SWORD: true
  STONE_AXE: true
  STONE_HOE: true
  STONE_PICKAXE: true
  STONE_SHOVEL: true
  WOODEN_SWORD: true
  WOODEN_AXE: true
  WOODEN_HOE: true
  WOODEN_PICKAXE: true
  SHIELD: true
  SHEARS: true
  TURTLE_HELMET: true
  TRIDENT: true
  FISHING_ROD: true
  BOW: true
materialNames:
  swordName: 剑
  bowName: 弓
  pickaxe: 镐
  spade: 铲
  hoe: 锄
  axe: 斧
  helmet: 头盔
  chestplate: 胸甲
  leggings: 护腿
  boots: 鞋子
  shears: 剪刀
  fishingRod: 钓鱼竿
  shield: 盾牌
  trident: 三叉戟
